parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments: [ '@http_kernel', '@request_stack', '@controller_resolver' ]
    App\EventListener\LogoutListener:
        arguments:
            $domain: '%env(AUTH0_DOMAIN)%'
            $clientId: '%env(AUTH0_CLIENT_ID)%'
            $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent }
    App\Controller\AuthenticationController:
        arguments:
            $oAuthUtils: '@hwi_oauth.security.oauth_utils'
